### ISSUE TITLE
Procedure not working on ESP and White Glow

### ISSUE THREAD

**Issue by JoergBrors** [mtniehaus/UpdateOS#1]
Hi,
we have enrolled several machines using the script embedded in the ESP of Autopilot. We install the latest Updates during the preparation of the device ( in white glow mode) and it works perfekt !! Now a month ago the deployment  stops. It finished the installation of updates (using this script)  and other Software ( machine part), and finaly reboot. After the reboot it check again the 
 first stage of autopilot an hang in the contacting MDM Server. The ESP defined timeout do not help and give no error. Please how i can find the responsible update and how I can exclude this.

Thanks Joerg

**Comment by TVMike** [comment]
Hi all,
I experience the same behavior with Windows 20H2.
After the ESP is done and the script was successful, there is no change in the version of the Windows Installation.
Same behavior is, when installing on Windows 21H2.

Maybe it is also required to mention, that we Switch the edition of Windows 10 20H2 from Pro to Enterprise during the user enrollment (see for that Microsoft E3 licensing).
Maybe you have an idea, what is necessary to push the latest updates on the devices, prior first use.
