### ISSUE TITLE
Install failure, Apps (0x81036502)

### ISSUE THREAD

**Issue by Bwells2023** [mtniehaus/UpdateOS#5]
Hello,

Looking for a way to apply windows updates during autopilot setup. Came across this option and started some test runs based of the setup instructions. During account setup I see the app failure below:

Apps(0x81036502)

It happened once I added the .intunewin app with the update. Once I remove it, the setup finished. I also tested ESP with just that PowerShell update app and failed. Have you seen this error before? and have a suggested resolution?

Thank you

**Comment by mtniehaus** [comment]
That error by itself just means that a timeout occurred.  Did you set a longer "Installation time required (mins)" value?

<img width="703" alt="image" src="https://github.com/mtniehaus/UpdateOS/assets/16982296/3a1196ea-ba90-4fd8-bcfa-84e59c96fac0">

**Comment by Bwells2023** [comment]
Hello,

Yes I had set to 120 minutes

![Screenshot 2024-02-02 at 10 43 02 AM](https://github.com/mtniehaus/UpdateOS/assets/133366294/c8b4f773-ddcc-4692-9511-837ff8578d7c)

**Comment by mtniehaus** [comment]
OK, then it would require digging deeper into the IntuneManagementExtension.log file to see what's up.

**Comment by HeyJudeRW** [comment]
Hi @Bwells2023 , did you try running the PS script manually with admin rights?

**Comment by Bwells2023** [comment]
Hello @HeyJudeRW,

Yes, I was able to run it locally.  I do have to set the execution policy to unrestricted. The issue on my end may be with the script not being signed. Right now, this is on hold for due to timing.

Thank you
