### ISSUE TITLE
Not all parameters are taken over, when re-running process

### ISSUE THREAD

**Issue by HeyJudeRW** [mtniehaus/UpdateOS#6]
The "ExcludeDrivers" parameters is not taken over, when re-launching 32-bit as a 64-bit process.
https://github.com/mtniehaus/UpdateOS/blob/a6c6c3f0d9cf4a83cc50751329fd01d11ec70d5d/UpdateOS/UpdateOS.ps1#L59
I tested with "@PSBoundParameters". but it errors out:
```
Cannot process argument transformation on parameter 'ExcludeDrivers'.
Cannot convert value "System.String" to type "System.Management.Automation.SwitchParameter". Boolean parameters accept
only Boolean values and numbers, such as $True, $False, 1 or 0.
```

**Comment by mtniehaus** [comment]
I checked in a (brute force) fix for this, so you won't need to do any workarounds.  Sorry about that.
