### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by th3nme** [mtniehaus/UpdateOS#8]
Hi @mtniehaus , 

Could you add a parameter to exclude the updates so that it only does drivers as well?

I'm looking for a way to only install drivers during Autopilot and have the CU's etc. apply later. This will also run a lot quicker than doing all updates. I'm currently achieving this with PSWindowsUpdate module but I like your method better.

Regards,

Nick

**Comment by mtniehaus** [comment]
Done :-)

**Comment by th3nme** [comment]
Legend, thank you!
