### ISSUE TITLE
Feature Request: Option to exclude feature updates

### ISSUE THREAD

**Issue by techhitnz** [mtniehaus/UpdateOS#9]
Hello there,

Big fan of your work - both while you were at Microsoft and now your oofhours blog.

I was wondering if you can modify the script to exclude the installation of Windows feature updates?  

Thank you

**Comment by mtniehaus** [comment]
I haven't seen it ever offer a feature update.  Do you have a log that shows it doing this?

**Comment by techhitnz** [comment]
Ah my mistake.  It appears you are right.  Sorry for causing confusion.  I'll close the ticket.
